### ISSUE TITLE
Unauthorized 401 Issue

### ISSUE THREAD

**Issue by manitapote** [osome-iu/osometweet#64]
When bearer token is not correct or expired,  _user_lookup() in api.py is not handling 401 status code.

**Comment by mr-devs** [comment]
Hi @manitapote! Very happy to see you're using the package.

If I understand you correctly, you ran into a situation where you gave the package a bad `bearer_token` and the package returned a 401 error from Twitter. Is that right? If so, this is not actually a problem for the `osometweet` package. 

For example, we can't possibly handle all of the potential errors that Twitter will throw - if the code breaks b/c you're using a bad `bearer_token` (as it should) then Twitter throwing that error for us isn't really a problem.

If this makes sense please go ahead and close the issue. Otherwise, feel free to share a bit of code to help clarify the issues you're seeing. Thanks!

**Comment by mr-devs** [comment]
To be clear, the fix for this problem is to provide a working `bearer_token`.

**Comment by manitapote** [comment]
I think the program should return the error message for this but code is trying to find "x-rate-limit-remaining" in line 590 in api.py

At least package can return the error notice of Twitter directly.

**Comment by mr-devs** [comment]
Can you share the code that you are running which creates the error message as well as the error message that you are seeing? There is no need to push any code - unless you would like to try and fix the problem (in that case, please do!) - just paste everything here. Thanks!

**Comment by mr-devs** [comment]
This seems to have gone stale so I'm going to close. @manitapote feel free to reopen and paste your code here if this is still a problem.
