### ISSUE TITLE
Streaming parameters for OAuth1a _make_one_request

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#86]
The `OAuth1a` `_make_one_request` internal method includes the `stream` and `json` parameters. (See [here](https://github.com/osome-iu/osometweet/blob/e65cc0963cfd3e5854eb25beab040e70b90d3985/osometweet/oauth.py#L125))

I have two questions:
1. It seems like the `json` parameter is not used, which I assume is a bug, **however**, whether to include it on the return line or delete it as a parameter depends on the next question...
2. It seems like, for V2, we cannot access the streaming endpoints using OAuth1a authorization (you can find this info by checking out my earlier [comment](https://github.com/osome-iu/osometweet/pull/75#discussion_r693366900) about this). Do we think that we should just remove `stream` and `json`?
    - If so, perhaps it's a good idea to include some sort of catch that throws an error if you try to access the streaming endpoints with OAuth1a? Too much?

**Comment by ChrisTorresLugo** [comment]
This issue is close to the point that I mentioned in another thread: https://github.com/osome-iu/osometweet/issues/87#issuecomment-904098115

The way in which I test endpoints during development is to import one of the OAuths and use the 'private' function make_requests. This allows me to iterate quickly by avoiding modifying the library code and reinstalling it. When I'm ok with the behavior, I migrate the code to a function in api.py. Having a limited number of options available in make_requests means that I have to modify and reinstall the library prior to being able go through my workflow. Not a ton of work, but additional work nonetheless.

Something similar happened to me in the past with tweepy. Their API isn't very flexible, which means that if a new endpoint is released and they haven't updated their library, there isn't an easy way to try it out without going through the steps of modifying+reinstalling the library.

If we think we can release new endpoints within a reasonable time after Twitter releases them, then this is not a problem. But if we can't, then we are limiting users.

**Comment by mr-devs** [comment]
Okay, this makes sense. 

Basically, it sounds like having the individual `_make_one_request` functions mirror one another means we get a bit of flexibility should things change in the future. This is sort of what I assumed and I think it's a good idea. The downside, I suppose, is that we are allowing users to make API requests that they aren't allowed to make - but I don't think that is really a big deal.

We still need to fix the unused `json` parameter bug. I'll open an issue for this.

@yangkcatiu I'm going to leave this open and give you some time to comment on this in case you wanted to add something to the discussion.

**Comment by yangkcatiu** [comment]
>  is that we are allowing users to make API requests that they aren't allowed to make

I'm OK with this. We have to assume that the users are familiar with Twitter's setting.

**Comment by mr-devs** [comment]
Awesome. Thanks, guys! I will close this discussion issue and we can track the open bug in #88.
